### ISSUE TITLE
Bugs in engine

### ISSUE THREAD

**Issue by PDKnight** [Nurgak/Cube-engine#8]
Hi, I've wanted to repair your bugs, but it's very hard.
Screenshot: http://i.imgur.com/95AeqZR.png
---
PS: Your engine's AWESOME :+1: ! By the way, I've changed it to load external map :P

**Comment by Nurgak** [comment]
Hi PDKnight,

That behaviour is normal. What happens is that planes that have vertices that reach "behind" the player cannot be drawn as it doesn't make sense mathematically and things start to look really weird. Here's [my question to StackOverflow](http://stackoverflow.com/questions/7378632/frustum-plane-calculus) from when I was building the Cube Engine about that exact issue.

Currently I'm just [removing vertices of planes that go behind the player](https://github.com/Nurgak/Cube-engine/blob/master/js/render.js#L598) and the triangle isn't drawn at all. For the affine texturing every square has to be divided to get 2 triangles, so you get this case where only part of the square is shown when one of the 4 vertices is hidden... that's unfortunately a limitation of making such a 3D engine. Technically you can calculate where the missing vertex is, but it's rather math intensive and having to do that for all nodes for every frame adds quite a lot of overhead.

The skewed textures are also normal, this is unfortunately one of the issues with affine texturing when up close to the node.

I suggest you use WebGL instead of my Cube Engine, that'll solve all your issues, plus this project doesn't take advantage of the computer's GPU and thus the performance is really bad.

Cheers,

Karl

**Comment by PDKnight** [comment]
Hi, Nurgak,

Thanks for explaining the bugs. Oh, can you please explain another question? [Why](http://jsfiddle.net/g1ew69zw/2/) canvas smooth the image, when it's smaller than the area, where canvas have to stretch/skew image?

I don't use WebGL, because It's too laggy for me (about 5 SPF [seconds per frame] :_D), so when you haven't good graphics, you won't enjoy the game.

By the way, why you draw images on canvas and you don't use elements to stretch/skew/other methods? It will be really good, because the PCs with bad graphics have about 5 FPS...

PS: Sorry for my really bad english, I'm just learner :D

**Comment by Nurgak** [comment]
These are not bugs, these "features" are inherent to the engine, OpenGL/WebGL do things at lower level and specifically address these issues so you don't have to.

I'm not really sure if I understand your question, if you're asking why the textures get anti-aliased then I don't know, when I wrote the code I had this issue and it turned out to be unfixable at the time, so I left it like that.

It's really not meant to be anything else than a learning experience. Please take a [look](http://voxeljs.com/) [at](http://threejs.org/examples/webgl_geometry_minecraft_ao.html) [alternatives](https://github.com/mitsuhiko/webgl-meincraft), it's really weird that you only get 5FPS... unless you're using a decade old PC.

**Comment by PDKnight** [comment]
Yes, I've got very old PC :D

I think you didn't understand, what I meant :(. As you can see, I've made two codes, where I use the `drawImage()` method to draw skewed image. Picture looks antialiased, but when I add some CSS and JS code, canvas will draw pixelated image:

### First code, with antialiasing:
[Demo](http://jsfiddle.net/g1ew69zw/3/)

JavaScript:
```javascript
function load()
{
    drawImage();
}
```
CSS:
```css
canvas{    
    border:1px solid #eee;
}
```
#### Result:
![First fiddle](http://i.imgur.com/norJYpA.png)

### Second code, without antialiasing:
[Demo](http://jsfiddle.net/g1ew69zw/2/)

JavaScript:
```javascript
function load()
{
    context.mozImageSmoothingEnabled = false;
	context.webkitImageSmoothingEnabled = false;
	context.imageSmoothingEnabled = false;
    
    drawImage();
}
```
CSS:
```css
canvas{
	image-rendering: optimizeSpeed;
	image-rendering: -moz-crisp-edges;
	image-rendering: -webkit-optimize-contrast;
	image-rendering: -o-crisp-edges;
	image-rendering: crisp-edges;
	-ms-interpolation-mode: nearest-neighbor;
    
    border:1px solid #eee;
}
```
#### Result:
![Second fiddle](http://i.imgur.com/YruwpiC.png)

I've tried to remove this terrible antialiasing, but without any result :(

**Comment by Nurgak** [comment]
I did try the exact same thing when I wrote the code, for some reason anti-aliasing cannot be disabled because of the way the affine texturing is done, go figure...

I thought since canvas was quite recent that a setting in the canvas object would be added at some point in the future to disable anti-aliasing.

**Comment by PDKnight** [comment]
Thanks for reply and explanation :) Also, I've found solution, how to draw triangle with vertices behind the player. It's bit difficult way, how to do it, but it's possible (using lines angles etc.)... :D If i'll have much more time, I'll try to do it. 

Again, your engine is really awesome, because it uses cavas, not WebGL (it's faster for decace old PCs :D)...but we have to wait for removing this browser canvas bugs.

You're very programming skilled, I'm bowing.

By the way, I've found another bug. When I walk just against the wall, I don't stop. Engine teleports me 4 blocks up:
### Before
![Bug-before](http://i.imgur.com/ZwI7LfF.png)
### After
![Bug-after](http://i.imgur.com/HbpTEdD.png)

Cheers,

Patrick

**Comment by Nurgak** [comment]
Cool, how did you do that? Can you do a pull request maybe?

I know about the teleporting bug, it's a little bit annoying I agree. I use it to get back to the surface when I dig myself underground: when there's a block over your head and you jump it teleports you on top of the highest block in that column. I discovered it after I had finished the project and then I wasn't motivated enough to fix it anymore. It's not a difficult one though: there's probably an issue with [collision detection against the surrounding nodes at head-level](https://github.com/Nurgak/Cube-engine/blob/master/js/player.js#L309).

**Comment by PDKnight** [comment]
I didn't programme it yet, but I want to do it, when I'll have much more time :D So when I'll done it, I'll pull a request :)


> ```javascript
if(this.position.y+this.height+0.2+this.delta.y >= node.y && this.position.y < node.y)
{
    this.delta.y = -0.01;
    this.velocity = 0;
    this.position.y = node.y-this.height-0.2;
}
```
Why 0.2, why delta? I'm so stupid :D I should understand your code before I'll want to help you :D

**Comment by Nurgak** [comment]
Frankly I don't remember anymore, this is why one should always avoid "magic numbers" and comment more... my bad. I think it was a quick fix for a similar problem.

**Comment by PDKnight** [comment]
That's OK! I'm very pleased that you commented a lot in files!!!

**Comment by PDKnight** [comment]
Okay, it's very hard to understand your code, sorry :(

**Comment by PDKnight** [comment]
I've found another bug :D This bug (I think) doesn't need to explain. But It's funny! :D

See X coordinates:
### Before:
![Bug-before](http://i.imgur.com/uMirTGn.png)
### After:
![Bug-after](http://i.imgur.com/kHx8y3s.png)

**Comment by Nurgak** [comment]
I don't know what to tell you, I think it's still related to the vertices going behind the player and being removed, the skewed textures have always been like that when up close to a node. The surfaces disappear completely if you get too near them because of the vertex issue, so basically you cannot hug walls or you risk seeing through them.
